### ISSUE TITLE
Release 2.3 checklist

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#10537]
- prepare
  - [ ] Complete [milestone items](https://github.com/prettier/prettier/milestones)
  - [ ] Run on other projects to check for regressions
  - [ ] Write release notes
    - use `scripts/draft-blog-post.js` to generate a blog post draft (a file named <code>*YYYY*-*MM*-*DD*-*version*.md</code> in [`website/blog`](https://github.com/prettier/prettier/tree/master/website/blog)) from `changelog_unreleased`
    - [prs-merged-since](https://npm.im/prs-merged-since) ([readme](https://github.com/suchipi/prs-merged-since#prs-merged-since)) may be useful
- publish
  - [ ] Run [release script](https://github.com/prettier/prettier/tree/master/scripts/release)
- postpublish
  - [ ] Merge release notes
  - [ ] Wait for release notes to deploy
  - [ ] Clean `changelog_unlreleased`
    - use `./scripts/clean-changelog-unreleased.js`
  - [ ] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode) account via TweetDeck
  - [ ] Close milestone
  - [ ] Send schema PR generated by `scripts/generate-schema.js` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json) if we added a new option.
  - [ ] Update the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) with possible changes

Then monitor [Twitter](https://twitter.com/search?q=%40PrettierCode&src=typed_query&f=live)/[GitHub](https://github.com/prettier/prettier/issues) for any immediate issues 😄

**Comment by fisker** [comment]
The schema in SchemaStore seems missing `meriyah` and `espree` [parser](https://github.com/SchemaStore/schemastore/blob/9f1f10f6abd6e7cab1db8adc35ce5bc5d96f5a90/src/schemas/json/prettierrc.json#L107), please add them when release.

**Comment by jpike88** [comment]
@thorn0 if the current release seems stable enough, are you able to get a ```next``` release out the door?

**Comment by sosukesuzuki** [comment]
@thorn0 Milestone items has been completed, do you have any plan to release next ver? Are there any blockers?

**Comment by thorn0** [comment]
@sosukesuzuki As you already saw, there are issues with the diffs in regression testing.

**Comment by francium** [comment]
@thorn0 

> proofreading the release notes (see the changelog_unreleased directory)

I didn't go thorough directory, but did review your PR here https://github.com/prettier/prettier/pull/10659

Found a few issues. Should I review that PR or something else? Please advise, first time contributing to this repo, I don't know your preferred workflow.

**Comment by fisker** [comment]
Just

> add comments to the diff

**Comment by fisker** [comment]
Mission accomplished.
