### ISSUE TITLE
Release 2.4 checklist

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#11359]
- prepare
  - [x] Figure out items that should be included in milestone
  - [x] Complete [milestone items](https://github.com/prettier/prettier/milestones)
  - [x] Run on other projects to check for regressions
    - https://github.com/prettier/prettier-regression-testing/issues/70
  - [x] Write release notes (#11457)
    - use `node scripts/draft-blog-post.mjs` to generate a blog post draft (a file named <code>*YYYY*-*MM*-*DD*-*version*.md</code> in [`website/blog`](https://github.com/prettier/prettier/tree/master/website/blog)) from `changelog_unreleased`
    - [prs-merged-since](https://npm.im/prs-merged-since) ([readme](https://github.com/suchipi/prs-merged-since#prs-merged-since)) may be useful
- publish
  - [x] Run [release script](https://github.com/prettier/prettier/tree/main/scripts/release)
- postpublish
  - [x] Merge release notes
  - [x] Wait for release notes to deploy
  - [x] Clean `changelog_unreleased`
    - use `node scripts/clean-changelog-unreleased.mjs`
  - [ ] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode) account via TweetDeck
  - [ ] Close milestone
  - [x] Send schema PR generated by `node scripts/generate-schema.js` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json) if we added a new option (https://github.com/SchemaStore/schemastore/pull/1820)
  - [x] Update the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) with possible changes
  - [x] Revert https://github.com/prettier/prettier/pull/11433 (https://github.com/prettier/prettier/pull/11481)

Then monitor [Twitter](https://twitter.com/search?q=%40PrettierCode&src=typed_query&f=live)/[GitHub](https://github.com/prettier/prettier/issues) for any immediate issues 😄

**Comment by sosukesuzuki** [comment]
@fisker @alexander-akait @thorn0 If you know items that should be included 2.4, please add it to [2.4 milestone](https://github.com/prettier/prettier/milestone/37)

**Comment by kachkaev** [comment]
Could we try to finish #10956? Happy to make any necessary amendments, just waiting for feedback ATM 🙏

**Comment by thorn0** [comment]
@kachkaev I've not forgotten about that PR. When I get time, this will be the first thing on my list.

**Comment by jd-0001** [comment]
Can you please consider PR https://github.com/prettier/prettier/pull/6644 for release?

Eagerly waiting for this.

**Comment by sosukesuzuki** [comment]
Sorry, I don't think there is consensus on adding an option for that purpose. So we cannot implement it in next release.

**Comment by sosukesuzuki** [comment]
Maybe we're not going to do a patch release until the 2.4 release, so I'll merge the PR for the new features

**Comment by sosukesuzuki** [comment]
@thorn0 Could you review #10956?

**Comment by sosukesuzuki** [comment]
If there are no problems, I will release 2.4 tomorrow night(UTC+9).

@fisker @alexander-akait Are you okay?

@kachkaev  So, I'm really sorry, but we may not be able to include #10956 in 2.4.

**Comment by kachkaev** [comment]
@sosukesuzuki no worries about #10956, I understand! Happy to wait for @thorn0’s review when he finds time, unless someone else wants to take a look at my PR 🙂 We can always release it as a patch.

**Comment by sosukesuzuki** [comment]
I start to release

**Comment by sosukesuzuki** [comment]
done
