### ISSUE TITLE
Support file URL in api

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#11396]
Support  `URL` anywhere accept paths.

- [x] [`prettier.resolveConfig(filePath [, options])`](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options) #15354
- [x] [`prettier.resolveConfigFile([filePath])`](https://prettier.io/docs/en/api.html#prettierresolveconfigfilefilepath) #15332
- [x] [`prettier.getFileInfo(filePath [, options])`](https://prettier.io/docs/en/api.html#prettiergetfileinfofilepath--options) #15360
- [x] `options.ignorePath` in [`prettier.getFileInfo(filePath [, options])`](https://prettier.io/docs/en/api.html#prettiergetfileinfofilepath--options)  #15364
- [ ] More...

Maybe also `options.filepath`
