### ISSUE TITLE
TODOs after migrate source to ESM

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#12356]
- [x] Try to inline `require()` modules, if we load all those modules will slow down prettier #12527
- [x] Remove `/vendors`, we don't need bundle them into cjs in `next` branch #12377
- [x] Check if we can migrate `src/common/third-party.cjs` to ESM #13092
- [x] Build script need an update
	- [x] Remove `isEsm` mark added temporarily #12450
	- [x] `srcipts/shims/**` to esm? #12371
- [ ] Currently, `require` and `__dirname` is replaced in build time, must be written in a specific way, try to improve it, maybe shim `module`, `url`, `path`?
- [x] Try to use `node:` protocol for buit-in modules
- [x] Re-enable `import/no-extraneous-dependencies` rule #12374
- [x] Re-enable rule to forbid `src/cli` import modules from other directories #13209
- [x] Add `please-upgrade-node` back, maybe after #12306 #12448
- [x] Fix "Integration Tests" on dev version, #12271, #12859
- [x] Replace `lodash` with `lodash-es` #12376
- [x] Improve evaluate plugin #12429

**I'll add more later**

**Comment by fisker** [comment]
Going to close this, one left, but not easy to fix.

- [ ] Currently, `require` and `__dirname` is replaced in build time, must be written in a specific way, try to improve it, maybe shim `module`, `url`, `path`?
