### ISSUE TITLE
Release 2.6

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#12410]
- prepare
  - [x] Complete [milestone items](https://github.com/prettier/prettier/milestones)
  - [x] Run on other projects to check for regressions (https://github.com/prettier/prettier-regression-testing/issues/161)
  - [x] Write release notes (https://github.com/prettier/prettier/pull/12412)
    - use `node scripts/draft-blog-post.mjs` to generate a blog post draft (a file named <code>*YYYY*-*MM*-*DD*-*version*.md</code> in [`website/blog`](https://github.com/prettier/prettier/tree/master/website/blog)) from `changelog_unreleased`
    - [prs-merged-since](https://npm.im/prs-merged-since) ([readme](https://github.com/suchipi/prs-merged-since#prs-merged-since)) may be useful
- publish
  - [x] Run [release script](https://github.com/prettier/prettier/tree/main/scripts/release)
- postpublish
  - [x] Merge release notes
  - [x] Wait for release notes to deploy
  - [x] Clean `changelog_unreleased`
    - use `node scripts/clean-changelog-unreleased.mjs`
  - [x] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode) account via TweetDeck
  - [ ] Close milestone
  - [x] Send schema PR generated by `node scripts/generate-schema.mjs` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json) if we added a new option.
      - https://github.com/SchemaStore/schemastore/pull/2139
  - [x] Update the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) with possible changes

Then monitor [Twitter](https://twitter.com/search?q=%40PrettierCode&src=typed_query&f=live)/[GitHub](https://github.com/prettier/prettier/issues) for any immediate issues 😄

**Comment by sosukesuzuki** [comment]
@fisker @duailibe @kachkaev If you know of a feature that should be included in 2.6, please add it to [2.6 milestone](https://github.com/prettier/prettier/milestone/39)

**Comment by sosukesuzuki** [comment]
I intend to make a release tomorrow or the day after.

**Comment by fisker** [comment]
The 2.6 milestone is empty now.

**Comment by sosukesuzuki** [comment]
I'll release 2.6 tomorrow (JST).

**Comment by sosukesuzuki** [comment]
released!
