### ISSUE TITLE
Release 2.7

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#12931]
- prepare
  - [x] Complete [milestone items](https://github.com/prettier/prettier/milestones)
  - [x] Run on other projects to check for regressions ( https://github.com/prettier/prettier-regression-testing/issues/203 )
  - [x] Write release notes ( #12966 )
    - use `node scripts/draft-blog-post.mjs` to generate a blog post draft (a file named <code>*YYYY*-*MM*-*DD*-*version*.md</code> in [`website/blog`](https://github.com/prettier/prettier/tree/master/website/blog)) from `changelog_unreleased`
    - [prs-merged-since](https://npm.im/prs-merged-since) ([readme](https://github.com/suchipi/prs-merged-since#prs-merged-since)) may be useful
- publish
  - [x] Run [release script](https://github.com/prettier/prettier/tree/main/scripts/release)
- postpublish
  - [x] Merge release notes
  - [x] Wait for release notes to deploy
  - [x] Clean `changelog_unreleased`
    - use `node scripts/clean-changelog-unreleased.mjs`
  - [x] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode) account via TweetDeck
  	- [x] @sosukesuzuki Will do it
  - [x] Close milestone
  - [x] Send schema PR generated by `node scripts/generate-schema.mjs` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json) if we added a new option.
  	- [x] No changes in this version 
  - [x] Update the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) with possible changes

Then monitor [Twitter](https://twitter.com/search?q=%40PrettierCode&src=typed_query&f=live)/[GitHub](https://github.com/prettier/prettier/issues) for any immediate issues 😄

**Comment by sosukesuzuki** [comment]
@fisker Please update milestones if you have task that should be landed in 2.7.

**Comment by fisker** [comment]
Want release with CI? https://github.com/prettier/prettier/pull/12591

**Comment by sosukesuzuki** [comment]
Ah it is great! I'll review it.

**Comment by glasser** [comment]
looking forward to the ability to use `<in/out T>` without breaking prettier :)

**Comment by sosukesuzuki** [comment]
@fisker I sent a DM to you in Discord, please check it.

**Comment by fisker** [comment]
Working on releasing v2.7

**Comment by fisker** [comment]
Having trouble add the bot as maintainer, working on it.

**Comment by fisker** [comment]
All done. Closing!
