### ISSUE TITLE
Plugins & tools support for v3

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#13616]
Prettier plugins interface will be breaking changed since v3.

So we need to investigate it works fine for major plugins.

Migration guide is here: https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F

### Official Plugins

- [x] [`@prettier/plugin-ruby`](https://github.com/prettier/plugin-ruby)
  - https://github.com/prettier/plugin-ruby/issues/1286
- [x] [`@prettier/plugin-pug`](https://github.com/prettier/plugin-pug)
  - https://github.com/prettier/plugin-pug/pull/411
- [x] [`@prettier/plugin-php`](https://github.com/prettier/plugin-php)
  - https://github.com/prettier/plugin-php/issues/2090
- [x] [`@prettier/plugin-xml`](https://github.com/prettier/plugin-xml)
  - https://github.com/prettier/plugin-xml/issues/616

### Community Plugins

- [x] [`prettier-plugin-svelte`](https://github.com/sveltejs/prettier-plugin-svelte)
  - https://github.com/sveltejs/prettier-plugin-svelte/issues/317
- [x] [`prettier-plugin-astro`](https://github.com/withastro/prettier-plugin-astro)
  - https://github.com/withastro/prettier-plugin-astro/pull/264
- [x] [`prettier-plugin-tailwindcss`](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)
  - https://github.com/tailwindlabs/tailwindcss/discussions/9602
- [ ] [`prettier-plugin-sort-imports`](https://github.com/trivago/prettier-plugin-sort-imports)
  - https://github.com/trivago/prettier-plugin-sort-imports/issues/177
- [x] [prettier-plugin-apex](https://github.com/dangmai/prettier-plugin-apex)
  - https://github.com/dangmai/prettier-plugin-apex/issues/673
- [x] [prettier-plugin-elm](https://github.com/gicentre/prettier-plugin-elm)
  - https://github.com/gicentre/prettier-plugin-elm/issues/30
- [ ] [prettier-plugin-erb](https://github.com/adamzapasnik/prettier-plugin-erb)
  - https://github.com/adamzapasnik/prettier-plugin-erb/issues/122
- [ ] [prettier-plugin-glsl](https://github.com/NaridaL/glsl-language-toolkit/tree/main/packages/prettier-plugin-glsl)
  - Maybe no maintained?
- [x] [prettier-plugin-go-template](https://github.com/NiklasPor/prettier-plugin-go-template)
  - https://github.com/NiklasPor/prettier-plugin-go-template/issues/96
- [x] [prettier-plugin-java](https://github.com/jhipster/prettier-java)
  - https://github.com/jhipster/prettier-java/issues/557
- [x] [prettier-plugin-jsonata](https://github.com/Stedi/prettier-plugin-jsonata)
  - https://github.com/Stedi/prettier-plugin-jsonata/issues/122
- [ ] [prettier-plugin-kotlin](https://github.com/Angry-Potato/prettier-plugin-kotlin)
  - Maybe no maintained?
- [x] [prettier-plugin-properties](https://github.com/eemeli/prettier-plugin-properties)
  - https://github.com/eemeli/prettier-plugin-properties/issues/7
- [ ] [prettier-plugin-rust](https://github.com/jinxdash/prettier-plugin-rust)
  - https://github.com/jinxdash/prettier-plugin-rust/issues/19
- [x] [prettier-plugin-sh](https://github.com/rx-ts/prettier/tree/master/packages/sh)
  - https://github.com/un-ts/prettier/issues/232
- [x] [prettier-plugin-solidity](https://github.com/prettier-solidity/prettier-plugin-solidity)
  - https://github.com/prettier-solidity/prettier-plugin-solidity/issues/747
- [x] [prettier-plugin-toml](https://github.com/bd82/toml-tools/tree/master/packages/prettier-plugin-toml)
  - Maybe no maintained.

## Tools

- [ ] [Jest](https://github.com/facebook/jest)
  - https://github.com/facebook/jest/issues/13495
- [x] [prettier-vscode](https://github.com/prettier/prettier-vscode)
  - https://github.com/prettier/prettier-vscode/pull/2947

**Comment by fisker** [comment]
@ssbarnea Looking at the code, I think it should still work for v3. Have you try use it with Prettier v3? (we have released alpha version for v3)

**Comment by ssbarnea** [comment]
@fisker I have being using it with v3 alpha in few project, but today i found the first one where it raises an exception, so I had to drop it (had only one TOML file in entire repo).

**Comment by jasikpark** [comment]
would love to see https://github.com/tamasfe/taplo/issues/73 picked up as a replacement, since it seems like the most maintained formatter for toml atm?

**Comment by ssbarnea** [comment]
@jasikpark While it might be really good, I really doubt that npm based project like prettier will want to add a rust dependency. Usually tools like this do not go outside their own ecosystem, for good reasons.

On the other hand, I would not mind doing some maintenance for revival of the current toml plugin if the project would be adopted under prettier github organization. I have the feeling that the current owner would not mind such a move.

@sosukesuzuki What do you think about this?

**Comment by bd82** [comment]
Hello @ssbarnea I would be quite happy to hand-over the TOML plugin...
Particularly as I am no longer actively maintaining it 😄

**Comment by jasikpark** [comment]
another obscure plugin: https://github.com/gregberge/svgr/tree/main/packages/plugin-prettier

**Comment by sosukesuzuki** [comment]
prettier-vscode v9.15.0 that supports Prettier v3 has been released

**Comment by jasikpark** [comment]
also the fork `@ianvs/prettier-plugin-sort-imports` https://github.com/IanVS/prettier-plugin-sort-imports

**Comment by aronmal** [comment]
https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/95

**Comment by mattrossman** [comment]
`prettier-plugin-astro` supports Prettier v3 as of v0.11.0

https://github.com/withastro/prettier-plugin-astro/releases/tag/v0.11.0

**Comment by so1ve** [comment]
Though toml plugin is outdated, it still works when using prettier@3. (wow)

**Comment by dummdidumm** [comment]
`prettier-plugin-svelte` supports Prettier v3 as of v3.0.0

https://github.com/sveltejs/prettier-plugin-svelte

**Comment by JounQin** [comment]
[prettier-plugin-toml](https://github.com/un-ts/toml-tools/tree/master/packages/prettier-plugin-toml) `>= 1.0.0` now supports Prettier v3

**Comment by ecmel** [comment]
[prettier-plugin-ejs](https://github.com/ecmel/prettier-plugin-ejs) >= 0.0.14 supports Prettier v3

**Comment by fisker** [comment]
Most plugins listed already updated, closing now.
