### ISSUE TITLE
Clean up TypeScript printer

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#14268]
- [x] It should be able to remove `printTypeScriptModifiers` after #14265 #14266 #14267
- [x] Double check changes in https://github.com/typescript-eslint/typescript-eslint/pull/4863
- [x] Apply changes from https://github.com/typescript-eslint/typescript-eslint/pull/6243 #14274
- [ ] ~Apply changes from https://github.com/typescript-eslint/typescript-eslint/pull/6274~ Only one place found maybe effected,  #14289
