### ISSUE TITLE
Release 3.1.0

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#15462]
- prepare
  - [x] Complete [milestone items](https://github.com/prettier/prettier/milestones)
  - [x] Run on other projects to check for regressions
    - https://github.com/prettier/prettier-regression-testing/issues/430
  - [x] Write release notes
    - use `node scripts/draft-blog-post.mjs` to generate a blog post draft (a file named <code>*YYYY*-*MM*-*DD*-*version*.md</code> in [`website/blog`](https://github.com/prettier/prettier/tree/master/website/blog)) from `changelog_unreleased`
    - [prs-merged-since](https://npm.im/prs-merged-since) ([readme](https://github.com/suchipi/prs-merged-since#prs-merged-since)) may be useful
- publish
  - [x] Run [release script](https://github.com/prettier/prettier/tree/main/scripts/release)
- postpublish
  - [x] Merge release notes ( https://github.com/prettier/prettier/pull/15503 )
  - [x] Merge blog post for `--experimental-ternaries` ( https://github.com/prettier/prettier/pull/15618 )
  - [ ] Wait for release notes to deploy
  - [ ] Clean `changelog_unreleased`
    - use `node scripts/clean-changelog-unreleased.mjs`
  - [ ] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode).
  - [ ] Close milestone
  - [ ] Send schema PR generated by `node scripts/generate-schema.mjs` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json) if we added a new option.
  - [ ] Update the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) with possible changes

Then monitor [Twitter](https://twitter.com/search?q=%40PrettierCode&src=typed_query&f=live)/[GitHub](https://github.com/prettier/prettier/issues) for any immediate issues 😄

**Comment by sosukesuzuki** [comment]
@fisker  If we've merged this PR, I'll release 3.1 this weekend. Is there anything else you would like to do?

**Comment by fisker** [comment]
No, I don't have time for other tasks before the release.

**Comment by moodyVlad** [comment]
Hello,
Any timeline for the release?
Really looking forward to the angular control flow changes.
Thanks

**Comment by sosukesuzuki** [comment]
I'll start release work 10am JST on November 13

**Comment by sosukesuzuki** [comment]
done
