### ISSUE TITLE
TODOs for babel v7.26.0

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#16801]
- [x] [#​16841](https://redirect.github.com/babel/babel/pull/16841) Always enable parsing of Flow enums  https://github.com/prettier/prettier/pull/16802
- [x] [#​16708](https://redirect.github.com/babel/babel/pull/16708) Add experimental format-preserving mode to @babel/generator #16804
- [x] [#​16732](https://redirect.github.com/babel/babel/pull/16732) Add kind to TSModuleDeclaration #16803
- [x] [#​16850](https://redirect.github.com/babel/babel/pull/16850) Enable import attributes parsing by default #16810

**Comment by sosukesuzuki** [comment]
I agree with you, option is 3 better

**Comment by fisker** [comment]
Close since all PRs created.
