### ISSUE TITLE
Release 3.4

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#16850]
- prepare
  - [x] Complete [milestone items](https://github.com/prettier/prettier/milestones)
  - [x] Run on other projects to check for regressions ( https://github.com/prettier/prettier-regression-testing/issues/445 )
  - [x] Write release notes ( https://github.com/prettier/prettier/pull/16851 )
    - use `node scripts/draft-blog-post.mjs` to generate a blog post draft (a file named <code>*YYYY*-*MM*-*DD*-*version*.md</code> in [`website/blog`](https://github.com/prettier/prettier/tree/master/website/blog)) from `changelog_unreleased`
    - [prs-merged-since](https://npm.im/prs-merged-since) ([readme](https://github.com/suchipi/prs-merged-since#prs-merged-since)) may be useful
- publish
  - [x] Run [release script](https://github.com/prettier/prettier/tree/main/scripts/release)
- postpublish
  - [x] Merge release notes
  - [x] Wait for release notes to deploy
  - [x] Clean `changelog_unreleased`
    - use `node scripts/clean-changelog-unreleased.mjs`
  - [x] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode) account via TweetDeck
  - [x] Close milestone
  - [x] Send schema PR generated by `node scripts/generate-schema.mjs` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json) if we added a new option.
  - [x] Update the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) with possible changes

Then monitor [Twitter](https://twitter.com/search?q=%40PrettierCode&src=typed_query&f=live)/[GitHub](https://github.com/prettier/prettier/issues) for any immediate issues 😄

**Comment by sosukesuzuki** [comment]
@fisker Any other issues that is should be included in 3.4?

**Comment by fisker** [comment]
I think we have fixed https://github.com/prettier/prettier/issues/16501, please check if they are already tested, maybe we can add a changelog for it.

**Comment by fisker** [comment]
Better fix this issue too https://github.com/prettier/prettier/issues/16812, but we can't test because jest issue https://github.com/jestjs/jest/issues/15363, just make sure it works and test on your machine.

Add extra allowed code here https://github.com/prettier/prettier/blob/e9d15b14026e8dd897806d23b9a6cca24b537504/src/config/prettier-config/load-external-config.js#L4 should fix the issue.

**Comment by fisker** [comment]
https://github.com/prettier/prettier/pull/16828
https://github.com/prettier/prettier/pull/16765
https://github.com/prettier/prettier/pull/16818 can be include if you have time to review, but can wait.

**Comment by fisker** [comment]
https://github.com/prettier/prettier/pull/7111 is ready, I think we can include it too.

**Comment by sosukesuzuki** [comment]
Thank you. Since #7111 are large and #16828 is in progress, we will postpone them to 3.5. However, lets release 3.5 as soon as possible.

**Comment by sosukesuzuki** [comment]
@fisker Okay, we can release 3.4 after https://github.com/prettier/prettier/pull/16857 is merged

**Comment by sosukesuzuki** [comment]
released

**Comment by fisker** [comment]
Good job!
