### ISSUE TITLE
[1.6] Tracking issue

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#2589]
I'm going to have more time in the coming weeks to do a proper release, so starting a issue to figure out what needs to be done:

- [ ] Write the changelog
- [x] Run the JSX ternary big change through Facebook codebase and any edge cases it finds
- [x] Investigate and fix JSX/fbt issue that prevented to release 1.5 to fb www repo. The fix is likely going to be inside of the fbt transform so not open source.

Correctness issues we should fix:
- [ ] Implement a tokenizer that extracts CSS comments and use prettier comment attachment instead of the current node-based comment that drops a lot of them #2127
- [x] Fix CSS issue with @import without semi-colon #2584 
- [ ] Fix import comment in flow parser #2555

**Comment by charlike** [comment]
What about #2434 ? Maybe missed in the list :wink:

**Comment by suchipi** [comment]
Let me know if there's anything I can help with in regard to findings with the JSX ternary stuff

**Comment by rattrayalex** [comment]
@vjeux where do we stand on this? Need any help?

**Comment by lydell** [comment]
IMO we should let @vjeux double the JSX stuff on the Facebook codebase, write the changelog and then release. The other things can be done later and shouldn't block the release.

**Comment by vjeux** [comment]
Yeah the blocker is me at this point. This summer has been super intense with bunch of vacation, family visiting, switching teams... it'll all go back to normal at the end of next week.

Last time I tried to update prettier on the main codebase at Facebook it didn't go smoothly and had to be reverted so I want to get it right this time.

Once we're past this issue, we should be able to go back to business as usual. I'm also pretty excited because it's going to enable us to use prettier for CSS at fb :)

**Comment by danawoodman** [comment]
Would it be possible to instead release a patch release with #2434? This would be such a huge feature yet is backwards compatible that it's a shame that it is just sitting around waiting to be released. I completely understand that you're busy @vjeux, perhaps there is another maintainer that could do such a minor release? If not, I imagine FB has some other developers that would be happy to jump in and help?

**Comment by vjeux** [comment]
I'm working on it right now, it's going to be resolved soon :)

**Comment by vjeux** [comment]
I just fixed all the issues I could find running it through the fb codebase and understood what was wrong with our custom `<fbt>`.
![image](https://user-images.githubusercontent.com/197597/29697510-788e79a4-8904-11e7-8ef2-ca7ff8d83ab2.png)

I'll get started writing the changelog now :)

**Comment by niftylettuce** [comment]
Is `"prettier"` field in `package.json` going to be supported soon?   The issues posted and commented on are misleading and all the issues referenced to this do not discuss this at all, or what version it will be available in.

**Comment by niftylettuce** [comment]
The reason I ask, is because it's very annoying to have three separate configurations for prettier:

* eslint/xo: https://github.com/prettier/eslint-plugin-prettier
* vim: https://github.com/prettier/vim-prettier
* lint-staged: https://github.com/okonet/lint-staged#automatically-fix-code-style-with-prettier-for-javascript--flow-or-typescript

**Comment by niftylettuce** [comment]
Also, I was not able to get `.prettierignore` or an ignore option in a `.prettierrc` file working.

**Comment by lydell** [comment]
@niftylettuce See #2434 for what Prettier 1.6 will support. The readme is a bit confusing right now, because it refers to `master` (what will become 1.6), while the latest _released_ version is 1.5.3 (which does not support any kind of configuration file).

**Comment by vjeux** [comment]
I'm done writing the release notes, I'd love some review from people with access to the repo that can read it: https://github.com/prettier/prettier/releases/tag/untagged-3197ffbe0b32929f207d

cc @lydell, @azz, @josephfrazier, @rattrayalex

**Comment by existentialism** [comment]
@vjeux LGTM, nice work!

Small nit:

> styled-components _has_ a lot of different variants

**Comment by vjeux** [comment]
@existentialism feel free to edit it directly, I'm sure that there are a bunch of English typos :)

**Comment by existentialism** [comment]
Just made a few small edits: https://github.com/prettier/prettier/releases/tag/untagged-75a9874eacb2f71c8a1c

**Comment by vjeux** [comment]
I just published prettier@1.6.0-beta to npm. Please let me know if you can spot anything issue with it. I may do a proper release this weekend or on monday.

**Comment by azz** [comment]
Just made a couple of small edits to the notes - mainly noting we support `.prettierrc`, not `.prettierconfig`.

**Comment by vjeux** [comment]
@azz: feel free to expand on the config section if there are relevant details that are useful :)

**Comment by azz** [comment]
I added a link to the relevant section of the readme.

**Comment by ikatyang** [comment]
Shouldn't this be marked as `beta` tag?

![image](https://user-images.githubusercontent.com/8341033/29738249-d53a5b26-8a50-11e7-9ef8-a5befdc997ea.png)

**Comment by vjeux** [comment]
@ikatyang oh wow good call, I put the latest tag back to the other one! thanks!

**Comment by adamroyle** [comment]
I get `error Command failed with exit code 1.` when using `--list-different`, but *only* when I've executed prettier through a package.json script and prettier has modified some files.

Prettier formats the files correctly (and there are no errors in my files), just the exit code is 1.

**Comment by ikatyang** [comment]
@adamroyle 

[`--list-different`](https://github.com/prettier/prettier#--list-different)

Another useful flag is `--list-different` (or `-l`) which prints the filenames of files that are different from Prettier formatting. **If there are differences the script errors out**, which is useful in a CI scenario.

**Comment by azz** [comment]
@vjeux I just added the TS2.5 support and the computed property change (#2670) to the release notes.

proposal-optional-chaining (#2572) is missing from the release notes. Was that intentional due to it being an early stage proposal?

**Comment by danawoodman** [comment]
Can the branch be pushed to git?

**Comment by vjeux** [comment]
@azz: I must have skipped it, there was a bunch of commits, not intentional.

**Comment by danawoodman** [comment]
@vjeux can we push tag to git?

**Comment by SimenB** [comment]
Close this?
