### ISSUE TITLE
Breaks child task list items in GFM (GitHub Flavored Markdown) files

### ISSUE THREAD

**Issue by iki** [prettier/prettier#3295]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqABABwIYCcEzoA2AlgM6EnwC2AOlPek0xmABYlEAmx5lN9ehgDaADwC6WPAXQxsZANa8K6KnDoMozFujGT2nHnMXL+6+iAA0ICJhgloZZKHkxkAM2xEycawCNcbDAFOBgAZRwwEigAc2QYXABXXxAuCDAPLx9raJ9cGAAFQJjqbEzvFIArMlEAIUDg0LDsajgAGWi4cuybRJhMPoAmbpScXDzkEFLcBTSAdygrEExcaJgAdRIuGDZkAA4ABmsViB91wMx4pJT8AEdEknwi7BKypE8K6x9qEivkr+iMSIcAAiokIPARtY5H5NttdkhBtDApxAQBhCDUUqTKDQLrWRI+AAq2D8TneWTgAF8qUA)
```sh
--parser markdown
```

**Input:**
```markdown
* parent list item

     * child list item

* [x] parent task list item

     * [x] child task list item

```

**Output:**
```markdown
* parent list item

  * child list item

* [x] parent task list item

      * [x] child task list item

```

**Expected behavior:**

Child task list items should use the same indent (2 spaces) as list items. The used indent of 6 spaces breaks them, as GFM only uses up to 5 spaces for child list items indent, [see sample](https://gist.github.com/iki/c415fbf7f4c214f8a3a554219cf4cc35)
