### ISSUE TITLE
1.9 Release

### ISSUE THREAD

**Issue by suchipi** [prettier/prettier#3333]
It's probably about time for a 1.9 release.

TODO:
* [x] Identify outstanding issues and PRs that we want in 1.9
* [x] Gather list of PRs merged since last release
* [x] Write changelog
* [x] Do the release
* [x] Uncomment docs/etc that needed to remain commented until post-release

https://github.com/prettier/prettier/milestone/7

**Comment by duailibe** [comment]
I believe #3255 and #3237 would be nice.

**Comment by suchipi** [comment]
I created a release:1.9 label but milestones are more appropriate for this, I'll remove the label

**Comment by suchipi** [comment]
I've added (I think) all of the PRs merged since 1.8.2 to the 1.9 milestone.

**Comment by vjeux** [comment]
Would be nice to get it released this week if possible. We should strive to get new popular syntax support like `<>` in a timely fashion so that people don't see prettier as a bottleneck.

**Comment by duailibe** [comment]
I'll start the release post this time.

**Comment by duailibe** [comment]
Changelog draft done!

**Comment by vjeux** [comment]
For people with commit access to the repo, you can see it here: https://github.com/prettier/prettier/releases

It's pretty awesome how few changes there were to CSS and JS. Prettier is getting good :)

**Comment by lydell** [comment]
I made some edits to the draft regarding GraphQL interpolations and CSS lowercasing.

**Comment by lipis** [comment]
Who ever is going to press the button, should tweet it as well at the same time :) I think most of the collaborators have access to the account.

**Comment by azz** [comment]
@duailibe I've added a few items to the release notes, but I've probably missed a couple, do you want to fill in the missing ones? When the #3255 build passes it can be merged and we should be good to do a release.

**Comment by duailibe** [comment]
I think only #3381 was missing, I added. Did you notice anything else?

**Comment by josephfrazier** [comment]
Oops, I added a bit more detail about #3255 and I think it overwrote your #3381 changes, @duailibe. Do you know if there's a way to recover them from the history?

**Comment by azz** [comment]
https://github.com/prettier/prettier/releases/tag/1.9.0

**Comment by azz** [comment]
I'm kind of busy today - someone want to do a patch release (1.9.1)?

**Comment by duailibe** [comment]
I can do it but I don't have access on npm

**Comment by vjeux** [comment]
@duailibe now you do :)

Make sure you do npm publish from the build folder and not the root :)

**Comment by duailibe** [comment]
Hopefully I didn't mess anything :)

**Comment by vjeux** [comment]
What I usually do is go back to all the issues that reported bugs that are fixed and comment saying that it’s now released

**Comment by ikatyang** [comment]
@duailibe You forgot to add the 1.9.1 changelog.

**Comment by duailibe** [comment]
You're right.

I noticed though the 1.7 and 1.8 patches didn't have a changelog.. so I did a simpler one, hope that's ok: https://github.com/prettier/prettier/releases/tag/1.9.1

**Comment by ikatyang** [comment]
Uh, I mean the `CHANGELOG.md`. 😂

**Comment by duailibe** [comment]
I didn't even know that was a thing :joy:

**Comment by duailibe** [comment]
I'd like to cut 1.9.2 before merging #3444 and #3449.. I wanted to wait for #3433 too but not sure if we should wait.

https://github.com/prettier/prettier/milestone/10?closed=1
Anything else to include?
