### ISSUE TITLE
1.15 Release

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#5297]
This issue tracks the 1.15 release progress.

- prepare
  - [x] Complete all [milestone items](https://github.com/prettier/prettier/milestone/21)
  - [x] Run on other projects to check for regressions
  - [x] Write release notes (#5296)
- publish
  - [x] Run [release script](https://github.com/prettier/prettier/tree/master/scripts/release)
- postpublish
  - [x] Merge release notes (#5296) and rationale updates (#5332)
  - [x] Wait for release notes to deploy
  - [x] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode) account via TweetDeck
    > _We just landed HTML, Angular, Vue and MDX support among other great features in the latest 1.15 version!_
    > 
    > _Grab it while it's hot and spread the word :)_  
    > [Link to the blog post]
  - [ ] Close this issue
  - [ ] Close milestone
  - [ ] Send schema PR generated by `scripts/generate-schema.js` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json).
  - [ ] Update the [Release Checklist on wiki](https://github.com/prettier/prettier/wiki/Release-Checklist)

Then monitor Twitter/GitHub for any immediate issues 😄

**Comment by lipis** [comment]
What about the #5327, are we going to include it in this release? Was it discussed?

**Comment by lipis** [comment]
One down! A few to go..

**Comment by lipis** [comment]
If the checklist is much smaller now we should update it in the wiki as well: https://github.com/prettier/prettier/wiki/Release-Checklist

**Comment by j-f1** [comment]
Ran it on GitHub Desktop: https://github.com/desktop/desktop/pull/6092

**Comment by ikatyang** [comment]
Done. https://twitter.com/PrettierCode/status/1059977485985726465

**Comment by beeman** [comment]
Thanks for all the effort you put in getting HTML to work with prettier @ikatyang!! Highly appreciated! 🙇🏻‍♂️
