### ISSUE TITLE
1.16 Release

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#5735]
This issue tracks the 1.16 release progress. I should be able to write the blog post next week but feel free to take this work over if you're interested (cc @prettier/core).

- prepare
  - [x] Complete [milestone items](https://github.com/prettier/prettier/milestone/22)
  - [x] Run on other projects to check for regressions
    - `npm install prettier/prettier`
  - [x] Write release notes
    - add a Markdown file named <code>*YYYY*-*MM*-*DD*-*version*.md</code> in [`website/blog`](https://github.com/prettier/prettier/tree/master/website/blog)
      - -> #5752
    - [prs-merged-since](https://npm.im/prs-merged-since) may be useful
- publish
  - [x] Run [release script](https://github.com/prettier/prettier/tree/master/scripts/release)
- postpublish
  - [x] Merge release notes
  - [x] Wait for release notes to deploy
  - [x] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode) account via TweetDeck
  - [x] Close milestone
  - [x] Send schema PR generated by `scripts/generate-schema.js` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json) if we added a new option.
  - [x] Update the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) with possible changes

**Comment by j-f1** [comment]
For the release notes, I’m wondering if we should make a work-in-progress blog post for the next release and ask everyone to add information from their PR to it so we don’t need to write it all after the fact.

**Comment by suchipi** [comment]
@j-f1 great idea

**Comment by duailibe** [comment]
The problem is we don't know for sure when we'll do a minor or a patch release

**Comment by j-f1** [comment]
If we decide to make a patch release, we can just remove the relevant PRs from the WIP blog post.

**Comment by ikatyang** [comment]
Sounds good, we could add an `Unreleased` section in the `CHANGELOG.md` (or something similar) and move them to the blog post if we'd like to release a minor version, it should speed up our release process.

**Comment by ikatyang** [comment]
WIP blog post -> #5752

**Comment by ikatyang** [comment]
Done. https://twitter.com/PrettierCode/status/1086897608805609472

**Comment by lydell** [comment]
Thanks, @ikatyang. Awesome work, as always! :100:
