### ISSUE TITLE
Release 1.19 checklist

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#6469]
- prepare
  - [x] Complete [milestone items](https://github.com/prettier/prettier/milestone/32)
  - [x] Run on other projects to check for regressions
  - [x] Write release notes
    - #6787 add a Markdown file named [<code>2019-11-03-1.19.0.md</code>](https://github.com/prettier/prettier/blob/master/website/blog/2019-09-16-1.19.0.md) in [`website/blog`](https://github.com/prettier/prettier/tree/master/website/blog)
    - [prs-merged-since](https://npm.im/prs-merged-since) may be useful
- publish
  - [x] Run [release script](https://github.com/prettier/prettier/tree/master/scripts/release)
- postpublish
  - [x] Adjust release notes date
  - [x] Merge release notes
  - [x] Wait for release notes to deploy
  - [x] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode) account via TweetDeck
  - [x] Close milestone
  - [x] Send schema PR generated by `scripts/generate-schema.js` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json) if we added a new option.
  - [x] Update the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) with possible changes – opened #6887
  - [x] Close #3888

Then monitor [Twitter](https://twitter.com/search?q=%40PrettierCode&src=typed_query&f=live)/[GitHub](https://github.com/prettier/prettier/issues) for any immediate issues 😄

**Comment by evilebottnawi** [comment]
I think will be great update all possible dependencies before do release

**Comment by squidfunk** [comment]
Any updates on 1.19? When will it be released?

**Comment by lydell** [comment]
@squidfunk  We’ve finally ticked off all blocking items in the [1.19 milestone](https://github.com/prettier/prettier/milestone/32)!

**Comment by mrmckeb** [comment]
Is there a way to test this out? I'd be happy to run against a few projects to help test.

**Comment by lipis** [comment]
> Is there a way to test this out? I'd be happy to run against a few projects to help test.

```
npm install prettier/prettier
# or
yarn add prettier/prettier
```

**Comment by mrmckeb** [comment]
This is working well, thanks @lipis. I'll let you know if we have any issues over the coming days.

**Comment by lydell** [comment]
@prettier/core If anyone could help with “Run on other projects to check for regressions” that would be amazing!

**Comment by thorn0** [comment]
I see a couple of questionable changes like the following. This will surely cause complaints.

**Prettier pr-6787**
[Playground link](https://deploy-preview-6787--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEB6VACAtD3f8GFHG4AOATgJaxYDulAJjABYmEB8AOlJFAM4wM5OH1LQ+cDAF4MAQ1qzKglpT4A6ACTMYMUmoDmcGAB4AYhAuXLAZTjkAbpTBw1AESOKANn1eyYs9gAKbgwMAANZUkpUADMLNVk+ZgAPWIssBg9Kb1QNYABbAE8ASQYAXzCAGhCMYAwwWTBmOCQMFXVtXQBhRubKtsp8uAgAVxhWhp44TzsMMu4ASgBubhBKkAhSGEpxZFBZcnIIWgAFA4Q+ZBBZewhGNZAAI3JGgGsja1JG6n1kGHIRnB1tp8p4AOrMJQiL7OWz8JSURwwQpXMB8S7ragScgwE4vfT5WTIGKybxAkAAKz4yQAQi8wO8YNZZEMADLUODE0kSdZU5LWH4zACKIwg8C5ZPWX3I2KuyNIIjAVC2Dwo1BgYMYLGQAA4AAxSo4SMEvUhXCgiOz2TnrACOovgeM2lxQiSwUDgcEyDAewntlGEeNkBKJSBJkpAEnylD+APJfEFcBFYs5Ye55P8j01TGYyAATOt-l4fl0IPlCVcoNAbSARhIACqyR4u8M8kD2QHFKCZWDWJWULYAQW71mRMwlEjKZSAA)
```sh
--parser typescript
```

**Input:**
```tsx
// ------------------------------------------------print-width----------------->
const response = await this.$http.get<FoooooooooService.DetailsData>(
  `api/foo.ashx/foo-details/${myId}`,
  { cache: this.httpCache, timeout: canceler }
);

```

**Output:**
```tsx
// ------------------------------------------------print-width----------------->
const response = await this.$http.get<
  FoooooooooService.DetailsData
>(`api/foo.ashx/foo-details/${myId}`, {
  cache: this.httpCache,
  timeout: canceler
});

```

**Comment by lydell** [comment]
@brainkim When running `master` on some code bases I have access to, I got lots of improvements like this:

```diff
       return events;
     }),
     TE.chain(publishEventsToService(dryRun))
-  )().then(E.fold(err => console.error(err), _ => console.log("Went well")));
+  )().then(
+    E.fold(
+      err => console.error(err),
+      _ => console.log("Went well")
+    )
+  );

 ): E.Either<Error, { Bucket: string; Key: string }> =>
   pipe(
-    E.tryCatch(() => new URL(urlString), error => error as Error),
+    E.tryCatch(
+      () => new URL(urlString),
+      error => error as Error
+    ),
     E.map(url => ({

   if (client) {
-    client.close(timeoutMs).then(() => process.exit(1), () => process.exit(1));
+    client.close(timeoutMs).then(
+      () => process.exit(1),
+      () => process.exit(1)
+    );
   } else {
```

But I also got cases where the output kind of became worse:

```diff
 export const timestampOfFirstCommit = (timelines: Timelines): O.Option<Date> =>
-  pipe(
-    timelines,
-    everyCommitTimestamps,
-    A.sort(ordDate),
-    A.head
-  );
+  pipe(timelines, everyCommitTimestamps, A.sort(ordDate), A.head);

 ) => (msg: unknown) =>
   pipe(
     serviceEventFromMessage(msg),
-    TE.chain(
-      flow(
-        publishServiceEvent(analytics),
-        TE.mapLeft(nackFromError)
-      )
-    )
+    TE.chain(flow(publishServiceEvent(analytics), TE.mapLeft(nackFromError)))
   )().then(messageResponse(logger, msg));

   .catch((err: Error) => {
     logger.error(
-      pipe(
-        O.fromNullable(err.stack),
-        O.getOrElse(constant(err.message))
-      )
+      pipe(O.fromNullable(err.stack), O.getOrElse(constant(err.message)))
     );
     process.exit(1);
   });

     expect(
-      pipe(
-        Changelog.timestampOfFirstCommit([[commit]]),
-        O.toUndefined
-      )
+      pipe(Changelog.timestampOfFirstCommit([[commit]]), O.toUndefined)
     ).toStrictEqual(new Date(0));
   });

     ),
-    TE.chain(
-      flow(
-        getUploadUrl,
-        E.mapLeft(Errors.unknownError),
-        TE.fromEither
-      )
-    ),
+    TE.chain(flow(getUploadUrl, E.mapLeft(Errors.unknownError), TE.fromEither)),
     TE.map(url => ({
```

Thoughts?

EDIT: It’s difficult, though, because I like this change:

```diff
-        date_of_incident: pipe(
-          now,
-          subYears(5)
-        ),
+        date_of_incident: pipe(now, subYears(5)),
```

**Comment by brainkim** [comment]
@lydell This is an expected change but I do agree that some of examples become less readable. However, I don‘t think any of these examples are themselves completely unreadable; rather, I believe it‘s just the fact that you’re reading the code in the context of the diff which makes it feel unreadable. Consider:

```js
pipe(timelines, everyCommitTimestamps, A.sort(ordDate), A.head);
```
English: pipe `timelines` into `everyCommitTimestamps`, sort by date and get the head.

```js
pipe(O.fromNullable(err.stack), O.getOrElse(constant(err.message)))
```

Not sure what this does but I don’t think it’s unreadable.

```js
TE.chain(flow(publishServiceEvent(analytics), TE.mapLeft(nackFromError)))
```

```js
TE.chain(flow(getUploadUrl, E.mapLeft(Errors.unknownError), TE.fromEither)),
```

These two seem trickier to read, but I think this has more to do with calling `flow` within a call to `chain`. It takes a second to figure out whether the arguments passed to `flow` are passed to `flow` vs `TE.chain`.

I don’t think any of these changes are show-stoppers, but I clearly cannot be impartial here so it’s up to the core team to decide if these diffs cannot be tolerated. I think trying to split these call expressions onto multiple lines (without the hard-coding behavior from before) would require some more thought. Maybe the rule you want is: when call expressions are nested 3 or 4 levels deep, break the top call onto multiple lines for clarity. I don’t think this is a bad idea, insofar as I have trouble immediately scanning deeply-nested call expressions anyways, but this would have broader repercussions for prettier users.

**Comment by j-f1** [comment]
I [ran it on GitHub Desktop’s (OOP-heavy) codebase](https://github.com/desktop/desktop/pull/8576) and the only changes involved the printing of template strings. Prettier is becoming incredibly stable!

**Comment by lydell** [comment]
@j-f1 Good stuff!

@brainkim That makes sense. I think we can ship 1.19 as-is and take it from there.

**Comment by lipis** [comment]
let's do it.

**Comment by pie6k** [comment]
![image](https://user-images.githubusercontent.com/7311462/68147254-faf3a100-ff39-11e9-8fd3-6ff7ea4e7c5f.png)

**Comment by Domino987** [comment]
Do we have an ETA for this?

**Comment by thorn0** [comment]
1.18.2 can format code like this:
```js
class A {} class A {}
```

but `master` can't because Babel became more restrictive:
```
SyntaxError: Identifier 'A' has already been declared (1:18)
```

This looks like a breaking change, so before doing the release, it might make sense to try updating Babel to [7.7.0](https://github.com/babel/babel/releases/tag/v7.7.0) and enabling [error recovery](https://github.com/babel/babel/pull/10363).

**Comment by evilebottnawi** [comment]
@thorn0 good catch :+1:

**Comment by thorn0** [comment]
addressed in #6816

**Comment by hlhr202** [comment]
cant wait!! GJ!!

**Comment by EdenTurgeman** [comment]
Can't wait for full TS 3.7 support!

**Comment by brodybits** [comment]
I just raised PR #6853 that resolves a critical `yarn audit` issue, hope it can be part of the upcoming release. With the update from PR #6853, I verified that all other `yarn audit` issues are on devDependencies.

**Comment by waterfoul** [comment]
Any status or ETA on when this could happen? Anything anyone can do to help make this happen?

**Comment by evilebottnawi** [comment]
Tomorrow (Friday)

**Comment by kbradl16** [comment]
> Tomorrow (Friday)

What time are we expecting this to be released?

**Comment by lipis** [comment]
it's still Friday in some places :)

**Comment by lydell** [comment]
I tried to make the release today, but couldn’t get the release script to work. Will have to try again tomorrow. 😢

**Comment by buko106** [comment]
[prettier@1.19.0](https://www.npmjs.com/package/prettier/v/1.19.0) is out now!! thanks!!

**Comment by lydell** [comment]
Yeah, I finally managed to find a workaround… 😅
