### ISSUE TITLE
Release 2.0 checklist

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#7778]
- prepare
  - [x] Complete [milestone items](https://github.com/prettier/prettier/milestone/34)
  - [x] Run on other projects to check for regressions
    - `npm install prettier/prettier#next` to try it on your project
    - [playground for `next`](https://deploy-preview-6773--prettier.netlify.com/playground/)
  - [x] Write release notes
    - PR https://github.com/prettier/prettier/pull/7417 (Blog post for 2.0)
    - [prs-merged-since](https://npm.im/prs-merged-since) may be useful
- publish
  - [x] Run [release script](https://github.com/prettier/prettier/tree/master/scripts/release)
- postpublish
  - [x] Merge release notes
  - [x] Wait for release notes to deploy
  - [x] Reset `master` to `next`
  - [x] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode) account via TweetDeck
  - [ ] Close milestone
  - [x] Send schema PR generated by `scripts/generate-schema.js` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json) if we added a new option. - https://github.com/SchemaStore/schemastore/pull/978
  - [x] Update the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) with possible changes

Then monitor [Twitter](https://twitter.com/search?q=%40PrettierCode&src=typed_query&f=live)/[GitHub](https://github.com/prettier/prettier/issues) for any immediate issues 😄

**Comment by thorn0** [comment]
Something is really wrong with comments in Less, but it's difficult to isolate it. :(
