### ISSUE TITLE
Release 2.1 checklist

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#8882]
- prepare
  - [x] Complete [milestone items](https://github.com/prettier/prettier/milestones)
  - [x] Run on other projects to check for regressions
  - [x] Write release notes
    - use `scripts/draft-blog-post.js` to generate a blog post draft (a file named <code>*YYYY*-*MM*-*DD*-*version*.md</code> in [`website/blog`](https://github.com/prettier/prettier/tree/master/website/blog)) from `changelog_unreleased`
    - ~~replace "Prettier stable" and "Prettier master" in code examples with the actual versions ([example](https://github.com/prettier/prettier/commit/171bc96b58c0ebad702270389674eadfffec09d1))~~
    - [prs-merged-since](https://npm.im/prs-merged-since) ([readme](https://github.com/suchipi/prs-merged-since#prs-merged-since)) may be useful
    - PR: #8932
- publish
  - [x] Run [release script](https://github.com/prettier/prettier/tree/master/scripts/release)
- postpublish
  - [x] Merge release notes
  - [x] Wait for release notes to deploy
  - [x] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode) account via TweetDeck
  - [ ] Close milestone
  - [x] Send schema PR generated by `scripts/generate-schema.js` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json) if we added a new option.
    - https://github.com/SchemaStore/schemastore/pull/1213
  - [x] Update the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) with possible changes

Then monitor [Twitter](https://twitter.com/search?q=%40PrettierCode&src=typed_query&f=live)/[GitHub](https://github.com/prettier/prettier/issues) for any immediate issues 😄

**Comment by sosukesuzuki** [comment]
@evilebottnawi Let's discuss about what we should include next release, here! from: https://github.com/prettier/prettier/pull/8861#issuecomment-668741190.

> What is status of typescript@4, because I think we will need to do release for this too?

Ideally I think we need to support TS 4.0 in next release with default typescript parser(typescript-estree). But I'm not sure when typescript-estree will support all of features TS 4.0. We have already supported TS 4.0 features via Babel so I don't think there is a big problem if we release it as it is.

/cc @fisker

**Comment by fisker** [comment]
> so I don't think there is a big problem if we release it as it is.

I agree, and once it's done. We can still support it with a path release.

**Comment by JamesHenry** [comment]
@evilebottnawi I've been hands off for personal reasons in the recent past, so @bradzacher would be much better placed to give an update

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/2260

Just needs support for Labelled Tuple Elements.
I haven't had a chance to do it as I've been working on our own v4 release.
But if someone wants to go add it in now, then it can be released as soon as Monday.
It should be pretty simple to setup because it's just standard `Identifier` parsing.

I can probably take a look on the weekend?

**Comment by fisker** [comment]
We probably won't ship new version with beta version of TS4.0, so I don't think we need `typescript-eslint` support it before stable TS4.0 relase.

**Comment by bradennapier** [comment]
Hit RC today https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-rc/

**Comment by sosukesuzuki** [comment]
Results of Prettier next on other projects:

- typescript-eslint: https://github.com/sosukesuzuki/typescript-eslint/pull/1/files
- excalidraw: https://github.com/sosukesuzuki/excalidraw/pull/2/files
- eslint-plugin-vue: https://github.com/sosukesuzuki/eslint-plugin-vue/pull/1/files

**Comment by sosukesuzuki** [comment]
a regression found #8941

**Comment by fisker** [comment]
Can you right a  script for this step?

> replace "Prettier stable" and "Prettier master" in code examples with the actual versions

https://github.com/prettier/prettier/issues/8415

**Comment by sosukesuzuki** [comment]
> Can you write a script for this step?

Okay, I'll try to do.

**Comment by bradzacher** [comment]
Support for labelled tuple elements: https://github.com/typescript-eslint/typescript-eslint/pull/2378

**Comment by sosukesuzuki** [comment]
@bradzacher Thank you, could you tell me when will the PR be released?

**Comment by bradzacher** [comment]
Tomorrow morning!

**Comment by sosukesuzuki** [comment]
Great! We'll use next ts-eslint/parser and support labelled tuple elements on Prettier 2.1!

**Comment by fisker** [comment]
Regression on build script cause by #8639

Before, `require('parse-*')` is `Dynamic Require`, now it's not, I'll try to find a way or revert that PR.

**Comment by fisker** [comment]
🎆

**Comment by sosukesuzuki** [comment]
I've released! Let's do postpublish tasks.

**Comment by sosukesuzuki** [comment]
@lipis Can you tweet for https://prettier.io/blog/2020/08/24/2.1.0.html from [@PrettierCode](https://twitter.com/@prettiercode)?
