### ISSUE TITLE
`v2.1.2` patch release

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#9137]
Let's cherry-pick these PR commits into the `patch-release` branch and release it from there as `v2.1.2`

## regressions

- [x] #9068: GraphQL directives are not indented
  - #9116
- [x] #9096, #9123: Incorrect line breaks for CSS in JS
  - #9136
- [x] #9130: Unexpectedly doubles a blank line before a YAML comment
  - [x] #9143
  - [x] #9169 (Related)
- ~~#9155 Markdown: space normalisation between block langauge and the attributes does not work for spaceless curly brace~~

***

Anything else?

**Comment by KarenEfereyan** [comment]
@sosukesuzuki how will the cherry pick be done

**Comment by GrahamCampbell** [comment]
@KarenEfereyan `git cherry-pick`?

**Comment by sosukesuzuki** [comment]
Yes, I'm going to `git cherry-pick` above PR commits  into `path-release` branch then release the branch

**Comment by kachkaev** [comment]
Happy to submit a quick patch for #9155 if it’s not too late 🙂

**Comment by KarenEfereyan** [comment]
@GrahamCampbell yes

**Comment by fisker** [comment]
> I'll work on this

Who? @sosukesuzuki? @kachkaev said, he want work on it.

**Comment by sosukesuzuki** [comment]
Oh, I misunderstood. I'll edit issue description, sorry.

**Comment by skevy** [comment]
@sosukesuzuki what are the chance we could put out a patch release with the fixes that have already merged? Based on my read of https://github.com/prettier/prettier/issues/9155 it seems like it might be a bit more involved to fix (let me know if I’m wrong about that). If that’s the case, it might be good to just release what’s there now to unblock people on these regressions in 2.1?

**Comment by sosukesuzuki** [comment]
@skevy Yes, I think we can release with the fixes that have already merged.  @fisker @kachkaev What do you think?

**Comment by sosukesuzuki** [comment]
If they don't reply, I'll release 2.1.2 tomorrow.

**Comment by fisker** [comment]
I responsed with a thumb up, I'm okay to make a release, #9155 seems not going to get fixed for  a  while.

**Comment by skevy** [comment]
Awesome, thanks @sosukesuzuki and @fisker! My colleagues will be very happy to have pretty formatted GraphQL directives again. :)

**Comment by sosukesuzuki** [comment]
I've published [2.1.2](https://github.com/prettier/prettier/releases/tag/2.1.2)!
