### ISSUE TITLE
Release 2.2 checklist

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#9549]
- prepare
  - [x] Complete [milestone items](https://github.com/prettier/prettier/milestones)
    - See  #9482
  - [x] Run on other projects to check for regressions (https://github.com/sosukesuzuki/prettier-regression-testing/issues/8)
  - [x] Write release notes (#9589)
    - use `scripts/draft-blog-post.js` to generate a blog post draft (a file named <code>*YYYY*-*MM*-*DD*-*version*.md</code> in [`website/blog`](https://github.com/prettier/prettier/tree/master/website/blog)) from `changelog_unreleased`
    - [prs-merged-since](https://npm.im/prs-merged-since) ([readme](https://github.com/suchipi/prs-merged-since#prs-merged-since)) may be useful
- publish
  - [x] Run [release script](https://github.com/prettier/prettier/tree/master/scripts/release)
- postpublish
  - [x] Merge release notes
  - [x] Wait for release notes to deploy
  - [x] Clean changelog_unreleased
  - [x] Tweet from [`@PrettierCode`](https://twitter.com/PrettierCode) account via TweetDeck
  - [x] ~~Close milestone~~ we have no milestone for 2.2
  - [x] Send schema PR generated by `scripts/generate-schema.js` to [SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/prettierrc.json) if we added a new option.
  - [x] ~Open Prettier update issue on [prettier/pre-commit](https://github.com/prettier/pre-commit/issues/new?title=Update%20Prettier%20to%20%60v%7BVERSION%7D%60&body=Prettier%20has%20released%20%5B%60v%7BVERSION%7D%60%5D(https%3A%2F%2Fgithub.com%2Fprettier%2Fprettier%2Freleases%2Ftag%2F%7BVERSION%7D)%2C%20please%20update.)~ Moved to https://github.com/pre-commit/mirrors-prettier.
  - [x] Update the [release checklist](https://github.com/prettier/prettier/wiki/Release-Checklist) with possible changes
  - [x] https://github.com/prettier/prettier/pull/8937#issuecomment-722975649

Then monitor [Twitter](https://twitter.com/search?q=%40PrettierCode&src=typed_query&f=live)/[GitHub](https://github.com/prettier/prettier/issues) for any immediate issues 😄

**Comment by sosukesuzuki** [comment]
typescript-eslint now supports TS4.1 features(https://github.com/typescript-eslint/typescript-eslint/pull/2748). We may have to wait for the release of typescript-eslint.

**Comment by fisker** [comment]
Wasn't typescript-eslint upgrade blocked by #9119?

**Comment by sosukesuzuki** [comment]
I'm thinking about it...

**Comment by sosukesuzuki** [comment]
A good solution has also not occurred to me. Let's release 2.2 without TS 4.1 support for the `typescript` parser...

**Comment by thorn0** [comment]
One dumb idea for a solution is to count the number of `@` characters before and after formatting. If it's changed, discard the formatting and keep the input as is.

**Comment by fisker** [comment]
Can we merge these yaml fixes https://github.com/prettier/prettier/pull/9665 https://github.com/prettier/prettier/pull/9669 https://github.com/prettier/prettier/pull/9674

**Comment by sosukesuzuki** [comment]
I'll review.

**Comment by sosukesuzuki** [comment]
After an hour I begin to release.

**Comment by sosukesuzuki** [comment]
done
